model_path: /home/igragon/Projects/innopolis_thesis_2025/EEG-Salience-Image/base_models/stable-diffusion-2-1-base-fp16
vae_path: /home/igragon/Projects/innopolis_thesis_2025/EEG-Salience-Image/base_models/stable-diffusion-2-1-base-fp16
noise_scheduler_path: /home/igragon/Projects/innopolis_thesis_2025/EEG-Salience-Image/base_models/stable-diffusion-2-1-base-fp16

weight_dtype: fp16
use_amp: True

unet_lora_config:
  r: 128
  lora_alpha: 256

optimizer:
  _target_: torch.optim.AdamW
  lr: 1e-4

lr_scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingWarmRestarts
  T_0: 2000
  eta_min: 1e-5

criterion:
  _target_: torch.nn.MSELoss


batch_size: 8
dataset:
  _target_: src.datasets.EEGEmbToImgDataset
  image_latents_folder: /home/igragon/Projects/innopolis_thesis_2025/EEG-Salience-Image/data/images/training_images_latents
  subject_eeg_embeddings: /home/igragon/Projects/innopolis_thesis_2025/EEG-Salience-Image/data/emb_eeg/ATM_S_eeg_features_sub-08_train.pt
  average_repetitions: True

save_dir: /home/igragon/Projects/innopolis_thesis_2025/EEG-Salience-Image/runs
num_epochs: 32
save_period: 2
grad_accumulation_steps: 1
clip_grad_norm: 1.0
seed: 42

device: auto

num_inference_steps: 100
null_vector_probability: 0.1