data_config:
  dataset:
    _target_: src.datasets.EEGSaliencyDataset.EEGSaliencyDataset
    images_folder_path: /home/igragon/Projects/innopolis_thesis_2025/EEG-Salience-Image/data/images/training_images
    images_latents_folder_path: /home/igragon/Projects/innopolis_thesis_2025/EEG-Salience-Image/data/images/training_images_latents
    saliency_maps_foler_path: /home/igragon/Projects/innopolis_thesis_2025/EEG-Salience-Image/data/images/training_images_saliency_maps

  data_df: /home/igragon/Projects/innopolis_thesis_2025/EEG-Salience-Image/data/images/training_images.csv
  subject_eeg_embeddings: /home/igragon/Projects/innopolis_thesis_2025/EEG-Salience-Image/data/emb_eeg/ATM_S_eeg_features_sub-08_train.pt
  eeg_repetitions: 4

  batch_size: 2
  val_batch_size: 10
  average_repetitions: true

model_path: /home/igragon/Projects/innopolis_thesis_2025/EEG-Salience-Image/base_models/cerulean-dream-160-epoch-30-merged
vae_path: /home/igragon/Projects/innopolis_thesis_2025/EEG-Salience-Image/base_models/stable-diffusion-2-1-base
noise_scheduler_path: /home/igragon/Projects/innopolis_thesis_2025/EEG-Salience-Image/base_models/stable-diffusion-2-1-base

weight_dtype: fp32
use_amp: False

optimizer:
  _target_: torch.optim.AdamW
  lr: 1e-4

lr_scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingWarmRestarts
  T_0: 5000
  eta_min: 1e-5

criterion:
  _target_: torch.nn.MSELoss

save_dir: /home/igragon/Projects/innopolis_thesis_2025/EEG-Salience-Image/runs
num_epochs: 32
save_period: 1
grad_accumulation_steps: 4
clip_grad_norm: 1.0
seed: 42

device: auto

num_inference_steps: 25
null_vector_probability: 0.1

# resume_from: /home/igragon/Projects/innopolis_thesis_2025/EEG-Salience-Image/runs/dainty-sky-172/checkpoint-epoch-12.pth